### ISSUE TITLE
Fix cosmic-horizon

### ISSUE THREAD

**Issue by broVeider** [bro-n-bro/bro-proposals-tracking-bot#7]
Hello. 
Cosmic Horizon chain is causing the following error:
Traceback (most recent call last):
  File "get_data.py", line 85, in <module>
    save_data()
  File "get_data.py", line 82, in save_data
    asyncio.run(get_data())
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "get_data.py", line 51, in get_data
    proposals = await asyncio.gather(*tasks)
  File "get_data.py", line 20, in get_proposals
    props = [prop for prop in resp['proposals'] if prop['status'] == 'PROPOSAL_STATUS_VOTING_PERIOD']
KeyError: 'proposals'

**Comment by broVeider** [comment]
Thank you for prompt fix.
