### ISSUE TITLE
Latest composable update broke bot

### ISSUE THREAD

**Issue by altbro** [bro-n-bro/bro-proposals-tracking-bot#8]
Composable finance, centauri-1 chain 
```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./notifier.py", line 3, in <module>
    from get_data import save_data
  File "/get_data.py", line 92, in <module>
    save_data()
  File "/get_data.py", line 89, in save_data
    asyncio.run(get_data())
  File "/usr/local/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/get_data.py", line 58, in get_data
    proposals = await asyncio.gather(*tasks)
  File "/get_data.py", line 27, in get_proposals
    props = [prop for prop in resp['proposals'] if prop['status'] == 'PROPOSAL_STATUS_VOTING_PERIOD']
KeyError: 'proposals'
```

**Comment by altbro** [comment]
@bro-n-bro-0 make an issue with rpc bug at https://github.com/notional-labs/composable-centauri 
ping @bro-n-bro-99 to rise question in twitter

**Comment by alibabaedge** [comment]
We have the similar trouble. Can you help please?

**Comment by bro-n-bro-2** [comment]
Module is not implemented in cosmos sdk.
